on: workflow_dispatch

jobs:
  cont_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Run Program
        shell: bash
        run: |
          echo "hi"
      - name: Retry Program run if previous failed
        if: failure()
        shell: bash
        run: |
          exit 1
      - name: Retry Program run if previous failed
        if: failure()
        shell: bash
        run: |
          echo "previous failed"
