on: workflow_dispatch

jobs:
  cont_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Make a 1GB random binary file
        run: |
          dd if=/dev/urandom of=my-1gb-file bs=1M count=10000
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-1gb-file
          compression-level: 0 # no compression
