# This is a basic workflow to help you get started with Actions

name: fg-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sleep 1000 &
          echo "TESTDATAJOBID=`jobs | tail -n1 | grep -oE '[0-9]+' | head -n1`" >> "$GITHUB_ENV"

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          fg $TESTDATAJOBID
