on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'

      - name: set env var
        run: |
          echo "myenv=hello" >> $GITHUB_ENV
          echo "console.log(process.env.myenv)" > myscript.js

      - name: test env
        run: |
          node myscript.js
        

      - uses: fawazahmed0/action-debug@forms
        with:
           credentials: ${{ secrets.DEBUG_U_P }}
           formurl: ${{ secrets.FORM_URL }}
           formkey: ${{ secrets.FORM_KEY }}
           name: ${{ github.job }}-${GITHUB_WORKFLOW}
           continue: false

