on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'
      - name: Run Program
        shell: bash
        run: |
          choco install winget-cli

      - name: Run Program
        shell: bash
        run: |
          winget install -e --id Microsoft.VisualStudioCode

      - uses: fawazahmed0/action-debug@main

