on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: fawazahmed0/action-debug@main
      - shell: bash
        run: |
          sleep 30
          cloudflared --help
