on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: macos-13
    name: A job to say hello
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: '21.1.0'

          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'

      - uses: fawazahmed0/action-debug@main

