on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Run my Action
      id: run-action
      uses: actions/javascript-action@v1 # Commit with the `v1` tag
      with:
        milliseconds: 1000
