on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - shell: bash
        run: |
          node -e "console.log(process.env)"
          sleep 30
          cloudflared --help
