name: paidsupport

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for branch 1 and on start directory, command.txt file changes or by manually running the workflow from actions tab
on:
  issues:
    types: [opened]

jobs:
  createComment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Paid support is available for faster resolution. For paid support, please write mail to youtube-uploader@datascraping.pp.ua
