on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    name: A job to say hello
    steps:
      - uses: easimon/maximize-build-space@master



      - uses: fawazahmed0/action-debug@forms
        with:
           credentials: ${{ secrets.DEBUG_U_P }}
           formurl: ${{ secrets.FORM_URL }}
           formkey: ${{ secrets.FORM_KEY }}
           name: ${{ github.job }}-${GITHUB_WORKFLOW}
           continue: false
