on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-24.04
    name: A job to say hello
    steps:
      - uses: easimon/maximize-build-space@master

      - name: build openwrt
        shell: bash
        run: |
          git clone https://github.com/fawazahmed0/openwrt.git .
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          wget -O .config https://github.com/fawazahmed0/tiger/releases/download/v2/config.buildinfo
          make defconfig
          make V=s -j$(nproc)

      - uses: fawazahmed0/action-debug@forms
        with:
           credentials: ${{ secrets.DEBUG_U_P }}
           formurl: ${{ secrets.FORM_URL }}
           formkey: ${{ secrets.FORM_KEY }}
           name: ${{ github.job }}-${GITHUB_WORKFLOW}
           continue: false
