on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    name: A job to say hello
    steps:
      - uses: easimon/maximize-build-space@master

      - name: build openwrt
        continue-on-error: true
        shell: bash
        run: |
          git clone https://github.com/fawazahmed0/openwrt.git -b openwrt-21.02
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          sudo apt update -y
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
          cp tempconfig .config
          make defconfig
          make V=s -j$(nproc)
          
      - uses: fawazahmed0/action-debug@forms
        with:
           credentials: ${{ secrets.DEBUG_U_P }}
           formurl: ${{ secrets.FORM_URL }}
           formkey: ${{ secrets.FORM_KEY }}
           name: ${{ github.job }}-${GITHUB_WORKFLOW}
           continue: false
