# This is a basic workflow to help you get started with Actions

name: playgrite

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: 22.3.0

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm i playwright@1.45.0
          npx playwright install --with-deps
          echo "import { firefox } from 'playwright'; console.log(`launching`);await firefox.launch()" > script.mjs

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          node script.mjs
