on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '21.6.2'
          registry-url: 'https://registry.npmjs.org'
          
      - uses: fawazahmed0/action-debug@main

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
