name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for branch 1 and on start directory, command.txt file changes or by manually running the workflow from actions tab
on:


  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.12' 

      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      # Partial clone
      - name: Partial clone
        shell: bash
        run: |
          python --version
          python3 --version
          node --version
          pip --version
          pip3 --version


      - name: Setup tmate session
        uses: lhotari/action-upterm@v1

          
      - name: ssh
        if: always()
        shell: bash
        run: |
          echo ${USER}@${HOSTNAME}
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod 777 cloudflared-linux-amd64
          #sudo apt-get update -y
          #sudo apt-get install openssh-server -y
          sudo systemctl enable ssh --now
          sudo systemctl start ssh
          sudo pip3 install webssh
          sudo wssh --fbidhttp=False &
          sudo ./cloudflared-linux-amd64 --url http://localhost:8888

    
    
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3 
        with:
          limit-access-to-actor: false

      # Partial clone
      - name: Partial clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git clone $REPO .

      - name: ip
        shell: bash
        run: curl http://icanhazip.com

      - name: install squid & run squid
        id: cache-dir
        shell: bash
        run: | 
          sudo apt-get update
          sudo apt-get -y install squid3 
          sudo mv squid.conf /etc/squid/squid.conf
          sudo mv passwords /etc/squid/passwords
          sudo chmod 777 /etc/squid/squid.conf
          sudo chmod 777 /etc/squid/passwords
          sudo service squid restart


      - name: sleep
        shell: bash
        run: sleep 15m
