name: Deploy real prod

on:

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy real prod
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
          
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "testdocs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}         
