name: Deploy real prod

on:

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy real prod
    runs-on: ubuntu-latest
    steps:
      # Partial clone
      - name: Partial clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.wiki.git"
          git clone $REPO .
          echo "hello world" > second.md
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git add -A
          git commit -m 'Update'
          git push
          
    
