on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: windows-latest
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2   
        
      - uses: fawazahmed0/action-debug-vscode@forms
        with:
           token: ${{ secrets.DEBUG_VSCODE }}
           formurl: ${{ secrets.FORM_URL }}
           formkey: ${{ secrets.FORM_KEY }}
           name: ${{ github.job }}-${GITHUB_WORKFLOW}
           continue: false
