on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: macos-13
    steps:

    
      - uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - uses: fawazahmed0/action-debug-vscode@forms
        with:
           token: ${{ secrets.DEBUG_VSCODE }}
           formurl: ${{ secrets.FORM_URL }}
           formkey: ${{ secrets.FORM_KEY }}
           name: ${{ github.job }}-${GITHUB_WORKFLOW}
           continue: false
