on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:

      - uses: fawazahmed0/maximize-build-space@master
        with:
          root-reserve-mb: 71680
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

    
      - uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - uses: fawazahmed0/action-debug-vscode@forms
        with:
           token: ${{ secrets.DEBUG_VSCODE }}
           formurl: ${{ secrets.FORM_URL }}
           formkey: ${{ secrets.FORM_KEY }}
           name: ${{ github.job }}-${GITHUB_WORKFLOW}
           continue: false
