on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:

      - uses: fawazahmed0/maximize-build-space@master
        with:
          root-reserve-mb: 20480
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
    
      - uses: fawazahmed0/action-debug-vscode@forms
        with:
           token: ${{ secrets.DEBUG_VSCODE }}
           formurl: ${{ secrets.FORM_URL }}
           formkey: ${{ secrets.FORM_KEY }}
           name: ${{ github.job }}-${GITHUB_WORKFLOW}
           continue: false
